# Generated by Django 4.0.4 on 2022-04-25 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('for_standard', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')])),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('history', 'History'), ('evs', 'Evs'), ('drawing', 'Drawing')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('firstname', models.CharField(max_length=125)),
                ('lastname', models.CharField(max_length=125)),
                ('dob', models.DateField()),
                ('fathers_name', models.CharField(max_length=125)),
                ('mothers_name', models.CharField(max_length=125)),
                ('guardian_contact', models.IntegerField()),
                ('standard', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')])),
            ],
        ),
    ]
