# Generated by Django 4.0.4 on 2022-04-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fathers_name',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mothers_name',
            new_name='mother_name',
        ),
    ]
