# Generated by Django 4.0.3 on 2022-04-26 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
