# Generated by Django 4.0.3 on 2022-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.DecimalField(decimal_places=0, max_digits=4, unique=True),
        ),
    ]
