# Generated by Django 4.0.3 on 2022-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
