# Generated by Django 4.0.3 on 2022-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_id_alter_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=20),
        ),
    ]
